/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` TEXT NOT NULL,
  `phone` TEXT NULL,
  `nickname` TEXT NULL,
  `description` TEXT NULL,
  `password` TEXT NULL,
  `avatar_id` TEXT NULL)
 ENGINE=InnoDB;

CREATE INDEX `user_id_i`
  ON `user` (`user_id`);

CREATE INDEX `phone_i`
  ON `user` (`phone`);

CREATE INDEX `nickname_i`
  ON `user` (`nickname`);

